// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package crash_detection_regs_pkg;

    localparam CRASH_DETECTION_REGS_DATA_WIDTH = 32;
    localparam CRASH_DETECTION_REGS_MIN_ADDR_WIDTH = 3;
    localparam CRASH_DETECTION_REGS_SIZE = 'h8;

    typedef struct {
        logic [31:0] next;
    } crash_detection_regs__speed_threshold__val__in_t;

    typedef struct {
        crash_detection_regs__speed_threshold__val__in_t val;
    } crash_detection_regs__speed_threshold__in_t;

    typedef struct {
        logic [31:0] next;
    } crash_detection_regs__non_fatal_accel_threshold__val__in_t;

    typedef struct {
        crash_detection_regs__non_fatal_accel_threshold__val__in_t val;
    } crash_detection_regs__non_fatal_accel_threshold__in_t;

    typedef struct {
        crash_detection_regs__speed_threshold__in_t speed_threshold;
        crash_detection_regs__non_fatal_accel_threshold__in_t non_fatal_accel_threshold;
    } crash_detection_regs__in_t;

    typedef struct {
        logic [31:0] value;
    } crash_detection_regs__speed_threshold__val__out_t;

    typedef struct {
        crash_detection_regs__speed_threshold__val__out_t val;
    } crash_detection_regs__speed_threshold__out_t;

    typedef struct {
        logic [31:0] value;
    } crash_detection_regs__non_fatal_accel_threshold__val__out_t;

    typedef struct {
        crash_detection_regs__non_fatal_accel_threshold__val__out_t val;
    } crash_detection_regs__non_fatal_accel_threshold__out_t;

    typedef struct {
        crash_detection_regs__speed_threshold__out_t speed_threshold;
        crash_detection_regs__non_fatal_accel_threshold__out_t non_fatal_accel_threshold;
    } crash_detection_regs__out_t;
endpackage
