// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package registers_pkg;

    localparam REGISTERS_DATA_WIDTH = 32;
    localparam REGISTERS_MIN_ADDR_WIDTH = 4;
    localparam REGISTERS_SIZE = 'hc;

    typedef struct {
        logic [10:0] next;
    } registers__data_packet_buffer_write_ptr_reg__WPTR__in_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__WPTR__in_t WPTR;
    } registers__data_packet_buffer_write_ptr_reg__in_t;

    typedef struct {
        logic next;
    } registers__data_packet_buffer_status_reg__EMPTY__in_t;

    typedef struct {
        logic next;
    } registers__data_packet_buffer_status_reg__FULL__in_t;

    typedef struct {
        registers__data_packet_buffer_status_reg__EMPTY__in_t EMPTY;
        registers__data_packet_buffer_status_reg__FULL__in_t FULL;
    } registers__data_packet_buffer_status_reg__in_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__in_t WRITE_PTR;
        registers__data_packet_buffer_status_reg__in_t STATUS;
    } registers__in_t;

    typedef struct {
        logic [20:0] value;
    } registers__data_packet_buffer_write_ptr_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_write_ptr_reg__out_t;

    typedef struct {
        logic [10:0] value;
    } registers__data_packet_buffer_read_ptr_reg__RPTR__out_t;

    typedef struct {
        logic [20:0] value;
    } registers__data_packet_buffer_read_ptr_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_read_ptr_reg__RPTR__out_t RPTR;
        registers__data_packet_buffer_read_ptr_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_read_ptr_reg__out_t;

    typedef struct {
        logic [29:0] value;
    } registers__data_packet_buffer_status_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_status_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_status_reg__out_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__out_t WRITE_PTR;
        registers__data_packet_buffer_read_ptr_reg__out_t READ_PTR;
        registers__data_packet_buffer_status_reg__out_t STATUS;
    } registers__out_t;
endpackage
