// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef REGS_H
#define REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - crash_detection_regs::speed_threshold
#define CRASH_DETECTION_REGS__SPEED_THRESHOLD__VAL_bm 0xffffffff
#define CRASH_DETECTION_REGS__SPEED_THRESHOLD__VAL_bp 0
#define CRASH_DETECTION_REGS__SPEED_THRESHOLD__VAL_bw 32
#define CRASH_DETECTION_REGS__SPEED_THRESHOLD__VAL_reset 0x14

// Reg - crash_detection_regs::non_fatal_accel_threshold
#define CRASH_DETECTION_REGS__NON_FATAL_ACCEL_THRESHOLD__VAL_bm 0xffffffff
#define CRASH_DETECTION_REGS__NON_FATAL_ACCEL_THRESHOLD__VAL_bp 0
#define CRASH_DETECTION_REGS__NON_FATAL_ACCEL_THRESHOLD__VAL_bw 32
#define CRASH_DETECTION_REGS__NON_FATAL_ACCEL_THRESHOLD__VAL_reset 0x32

// Addrmap - crash_detection_regs
typedef struct __attribute__ ((__packed__)) {
    uint32_t speed_threshold;
    uint32_t non_fatal_accel_threshold;
} crash_detection_regs_t;


static_assert(sizeof(crash_detection_regs_t) == 0x8, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* REGS_H */
