// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef REGS_H
#define REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - registers::data_packet_buffer_write_ptr_reg
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__WPTR_bm 0x7ff
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__WPTR_bp 0
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__WPTR_bw 11
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__WPTR_reset 0x0
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__RESERVED_bm 0xfffff800
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__RESERVED_bp 11
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__RESERVED_bw 21
#define REGISTERS__DATA_PACKET_BUFFER_WRITE_PTR_REG__RESERVED_reset 0x0

// Reg - registers::data_packet_buffer_read_ptr_reg
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RPTR_bm 0x7ff
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RPTR_bp 0
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RPTR_bw 11
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RPTR_reset 0x0
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RESERVED_bm 0xfffff800
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RESERVED_bp 11
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RESERVED_bw 21
#define REGISTERS__DATA_PACKET_BUFFER_READ_PTR_REG__RESERVED_reset 0x0

// Reg - registers::data_packet_buffer_status_reg
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__EMPTY_bm 0x1
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__EMPTY_bp 0
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__EMPTY_bw 1
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__EMPTY_reset 0x1
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__FULL_bm 0x2
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__FULL_bp 1
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__FULL_bw 1
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__FULL_reset 0x0
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__RESERVED_bm 0xfffffffc
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__RESERVED_bp 2
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__RESERVED_bw 30
#define REGISTERS__DATA_PACKET_BUFFER_STATUS_REG__RESERVED_reset 0x0

// Addrmap - registers
typedef struct __attribute__ ((__packed__)) {
    uint32_t WRITE_PTR;
    uint32_t READ_PTR;
    uint32_t STATUS;
} registers_t;


static_assert(sizeof(registers_t) == 0xc, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* REGS_H */
